apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: default
spec:
  encryptedData:
    mongo-root-password: AgAloJf8dU/6COVOc17ZB3J/HT1r8X33hKC7Ou/S13A9l7W62HW97ZJLqx5pQ3fNANV2la3mDfNNDiXisWMylPA8+nTJyBDerYdFjgEye9KE/VMkGtBOmt+NA4nmcn/X+qctghm3vy/pI7I5H0Ei+moK004utb5gU3aSRIgFEuGM+20zr6RJQdpLTPKQknyIfCTsNbmH60alEpv4kfPPDER9wuQUKh3EsRPUrx+aG5wUjflkVWZfefzTTmhOXmi0oABjZQVy/eGrryO3yTRELQvqqH6TKYusI9AVdGBgrBaJXpmpmMgzo2Omoz+bvCT6RpvNIdwOa55BLeL0iTNAj8engGNpB8Xw4Dg6+U5IpLRR08Raa7N4Z4+g+VRbr7qo7Ufg3jjxs49YoVs1uJM41jmjrXnXU9uPWxt/axcaS+PBXuWSahgaGi0UYaONwD605gMa1VgHwVNtzUeklT8+G+83jdraarVDY7BzfP4VVfpHzaJZow2Xkgrn2TduC9eBkrhliqcw3jsPGw5oGEcwSyB78pxXqMe0+Vq3eVp4sxLzE+CPp5SjMj3ovZ2CwegDkGG7h+cWb5Q8A9ZHvlWlu31i768sopxiraKfa54Ut4mfnBeR6lIQOvQii6LyfWe6ou+FDhNabyuipTwa9lGLSULvNa+5I2rp68CpeN2QikMkSO3mp4aN8YHeMsyhNEIsHhdsDN9TSBE1QQ==
    mongo-root-username: AgBFEilhLGrXZR6hgGv33iAUwX24x86i978bGV8Z3p7fB1aJcaD+TwYMvHuNUP8J1juqls6NGM5VNm2KwjFFi/7TlBnvflRxLRztIBpyZF3mIjvxhOKLuZNy4XERV9WE/W553QJRixyzNqYmMMUuAKQ8UiRLNvGsoPCosjw89XdCWpBJvxgdi6S1nxAmxdIhu5CtgccDxj7KGeQ2RyjzjNLXybN16cvwGSUEePFkoj5cmH8IcwyQj43C3cQnioUk85icn4IezRWbi0BZmh3zNMXold/wiB6nUrYtWYeQ2d8odox+KsYP41OQ7CrL8PET6fnrcvezlwO9KxEJLFH8XwGTHzFv8xz2aeksl7P7z2ztbK/R1jc/Pz4WiK2yYZsFCXX8VwshQwZdULxLmmFHgZZWgcKb10kpqwwDlsfrBnomC5DPvoeI08YB7a4/3nPQR0yQNmO/i5eNauMHrqlaw6cSU2gnHfUgL4RvA7C1pmQbxevRmLNhA2M6JLKqQlYy/xygcvjQhu/m0mUfuDQ0RgllIK6qRE7akohl1NtsJUOdQG+qcZ77YgvduLzWmxIzl3gmiolngQMkANSCHKC3TnFn5BB7qECoPYgdDH9VyjWbJAQw665yIM5j7c0JnMH7TT1zFBP8TOfxY8Y7t2gWsr7kQETJ02+dPmmGlVSNNS43CIOiRyH3PBLYvAuy5TX0XbPaOjmJWsQ6eA==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: default
    type: Ophique

